### ISSUE TITLE
Since octokit/routes is archived, should this use the OpenAPI Description instead?

### ISSUE THREAD

**Issue by francisfuzz** [swinton/github-rest-apis-for-insomnia#77]
:wave: @swinton! 

I recently imported this and noticed there were some missing routes. Reading up on https://github.com/octokit/routes, it's deprecated (latest: v30.0.3) in favor of the OpenAPI Description:

https://github.com/github/rest-api-description/

I'm wondering if this repo should use that instead? Not quite sure how much work it would take to port over, but thought to raise this so others who rely on this are aware!

**Comment by francisfuzz** [comment]
Update: I discovered that OpenAPI is supported by Insomnia ([docs](https://support.insomnia.rest/article/172-importing-and-exporting-data)) and it's possible to import it directly. For example, the [OpenAPI Description for `api.github.com`](https://github.com/github/rest-api-description/blob/main/descriptions/api.github.com/api.github.com.json) is available, and Insomnia will do the Right Thing:tm: by importing its [raw version](https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json).

At this point, I'm wondering if we should just point folks to this method instead? 💭

**Comment by swinton** [comment]
@imjohnbo started to PR this: https://github.com/swinton/github-rest-apis-for-insomnia/pull/72

We felt this project was still helpful, since it also generates environment variables.
